[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
]
confidence-threshold = 0.8

[[licenses.clarify]]
name = "bit_field"
expression = "MIT OR Apache-2.0"
license-files = []

[[licenses.clarify]]
name = "linked_list_allocator"
expression = "MIT OR Apache-2.0"
license-files = []

[[licenses.clarify]]
name = "pic8259"
expression = "MIT OR Apache-2.0"
license-files = []

[[licenses.clarify]]
name = "spinning_top"
expression = "MIT OR Apache-2.0"
license-files = []

[[licenses.clarify]]
name = "x86_64"
expression = "MIT OR Apache-2.0"
license-files = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

[advisories]
ignore = []

