$ErrorActionPreference = "Stop"

$workspaceRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$outputPath = Join-Path $workspaceRoot "THIRD_PARTY_LICENSES.md"

$packages = @(
    cargo license --json --manifest-path (Join-Path $workspaceRoot "Cargo.toml") |
        ConvertFrom-Json
) |
    Where-Object { $_.name -ne "mana_os" } |
    Sort-Object name, version

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Third-Party Licenses")
$lines.Add("")
$lines.Add("This file is generated by `cargo-license` via `scripts/generate_third_party_licenses.ps1`.")
$lines.Add("Refresh it after dependency changes with `just licenses`.")
$lines.Add("")
$lines.Add("## Rust Crates")
$lines.Add("")
$lines.Add("| Crate | Version | License | Repository |")
$lines.Add("| --- | ---: | --- | --- |")

foreach ($package in $packages) {
    if ($package.name -eq "mana_os") {
        continue
    }
    $license = if ([string]::IsNullOrWhiteSpace($package.license)) { "UNKNOWN" } else { $package.license }
    $repository = if ([string]::IsNullOrWhiteSpace($package.repository)) { "-" } else { $package.repository }
    $lines.Add("| $($package.name) | $($package.version) | $license | $repository |")
}

$lines.Add("")
$lines.Add("## Binary Assets")
$lines.Add("")
$lines.Add('The repository includes esp/Inter.ttf and esp/NotoSansJP.ttf.')
$lines.Add("Before redistribution, verify the exact upstream source and font license text for these files.")

[System.IO.File]::WriteAllText(
    $outputPath,
    ($lines -join [Environment]::NewLine) + [Environment]::NewLine,
    [System.Text.UTF8Encoding]::new($false)
)
