param(
    [int]$TimeoutSeconds = 30,
    [string]$SerialLog = "storage-smoke-serial.log"
)

$ErrorActionPreference = "Stop"

if (Test-Path $SerialLog) {
    Remove-Item -LiteralPath $SerialLog -Force
}

New-Item -ItemType Directory -Force -Path "esp\EFI\BOOT" | Out-Null
Copy-Item -LiteralPath "target\x86_64-unknown-uefi\debug\mana_os.efi" `
    -Destination "esp\EFI\BOOT\BOOTX64.EFI" -Force

$arguments = @(
    "-display", "none",
    "-no-reboot",
    "-drive", "if=pflash,format=raw,readonly=on,file=OVMF.fd",
    "-drive", "format=raw,file=fat:rw:esp",
    "-drive", "file=disk.img,if=none,id=drive0,format=raw",
    "-device", "ahci,id=ahci0",
    "-device", "ide-hd,drive=drive0,bus=ahci0.0",
    "-serial", "file:$SerialLog",
    "-monitor", "none"
)

$qemu = Start-Process -FilePath "qemu-system-x86_64" `
    -ArgumentList $arguments `
    -PassThru `
    -WindowStyle Hidden

$deadline = (Get-Date).AddSeconds($TimeoutSeconds)
$expectedPatterns = @(
    "Persistent block-device service registered",
    "AHCI DMA setup verified: command_list_typed=true received_fis_typed=true command_table_typed=true data_buffer_typed=true",
    "Registered block device",
    "Backup boot sector validated",
    "FSInfo: sector=1",
    "Registered FAT32 file backend for virtual filesystem",
    "Registered FAT32 file backend for virtual filesystem: path=/disk/bin/smoke_demo",
    "Registered FAT32 file backend for virtual filesystem: path=/disk/bin/file_demo",
    "Registered FAT32 file backend for virtual filesystem: path=/disk/bin/user_shell",
    "Disk file smoke read",
    "Pipeline command smoke passed",
    "ManaOS Kernel is alive\.",
    "Invalid ELF rejection smoke passed",
    "Frame allocator self-checks passed: .*released_frame_reuse=true",
    "Frame allocator self-checks passed: .*typed_frame_start=true",
    "Memory address wrapper self-checks passed: user_virtual_address=true",
    "Memory address wrapper self-checks passed: .*user_page_start=true kernel_page_start=true",
    "Memory address wrapper self-checks passed: .*kernel_page_start=true user_virtual_range=true user_range_page_bounds=true user_copy_ranges=true checked_conversions=true",
    "Memory address wrapper self-checks passed: .*frame_count=true",
    "Memory address wrapper self-checks passed: .*page_count=true",
    "Kernel virtual range allocator self-checks passed: non_overlapping_reuse=true exhaustion_rejection=true kernel_range_start_typed=true",
    "ACPI parser self-check passed: rsdp=true root_table=true madt=true physical_addresses_typed=true",
    "ACPI root table verified",
    "source\s+= uefi_acpi[12]",
    "root_table\s+= (xsdt|rsdt)",
    "root_address\s+= 0x[0-9a-f]+",
    "entries\s+= [1-9][0-9]*",
    "checksum\s+= true",
    "root_physical_addresses_typed\s+= true",
    "ACPI MADT verified",
    "local_apic\s+= 0x[0-9a-f]+",
    "pc_at_compatible\s+= (true|false)",
    "ioapics\s+= [1-9][0-9]*",
    "madt_physical_addresses_typed\s+= true",
    "ACPI interrupt topology verified",
    "retained_local_apics\s+= [1-9][0-9]*",
    "retained_ioapics\s+= [1-9][0-9]*",
    "topology_truncated\s+= false",
    "ioapic0_address\s+= 0x[0-9a-f]+",
    "legacy_irq0_flags\s+= 0x[0-9a-f]+",
    "x2apic0_present\s+= (true|false)",
    "topology_physical_addresses_typed\s+= true",
    "APIC routing provider configured",
    "local_apic_supported\s+= true",
    "local_apic_address\s+= 0x[0-9a-f]+",
    "local_apic_enabled\s+= true",
    "ioapic_address\s+= 0x[0-9a-f]+",
    "legacy_irq_routes\s+= [1-9][0-9]*",
    "route_truncated\s+= false",
    "Interrupt controller backend initialized: legacy_pic_initialized=false legacy_fallback_enabled=false legacy_pic_masked_for_apic=true master_mask=0xff slave_mask=0xff",
    "IOAPIC redirection plan verified",
    "entries\s+= 3",
    "truncated\s+= false",
    "timer_vector\s+= 32",
    "timer_masked\s+= false",
    "keyboard_vector\s+= 33",
    "mouse_vector\s+= 44",
    "Local APIC MMIO mapped: address=0x[0-9a-f]+ size=4096 pages=1 apic_mmio_address_typed=true page_count_typed=true physical_page_start_typed=true",
    "Local APIC EOI provider verified: configured=true routing_active=false software_enabled=(true|false) local_apic_address=0x[0-9a-f]+ local_apic_id=.* version=0x[0-9a-f]+ max_lvt_entry=[1-9][0-9]* spurious_vector=0x[0-9a-f]+",
    "IOAPIC MMIO mapped: address=0x[0-9a-f]+ size=4096 pages=1 apic_mmio_address_typed=true page_count_typed=true physical_page_start_typed=true",
    "IOAPIC redirection staging verified",
    "staged\s+= 3",
    "readback_matches\s+= true",
    "masked\s+= true",
    "out_of_range_entries\s+= 0",
    "IDT timer entry initialized: address=0x[0-9a-f]+ timer_entry_typed=true",
    "SYSCALL MSR initialized: lstar=0x[0-9a-f]+ syscall_entry_typed=true",
    "IOAPIC routing activated: entries=3 activated=3 readback_matches=true routing_active=true masked=false local_apic_software_enabled=true legacy_pic_masked=true out_of_range_entries=0 timer_low_readback=0x[0-9a-f]+ timer_high_readback=0x[0-9a-f]+ keyboard_low_readback=0x[0-9a-f]+ keyboard_high_readback=0x[0-9a-f]+ mouse_low_readback=0x[0-9a-f]+ mouse_high_readback=0x[0-9a-f]+ apic_eoi_count=0 legacy_eoi_count=0",
    "Local APIC timer calibration started: configured=true armed=true masked=true address=0x[0-9a-f]+ apic_mmio_address_typed=true vector=32 divide=16 lvt_timer=0x[0-9a-f]+ divide_config=0x3 initial_count=[1-9][0-9]* current_count=[0-9]+ start_ticks=[0-9]+",
    "Dynamic kernel mapping lifecycle self-check passed: map=true unmap=true virtual_reuse=true physical_reuse=true",
    "User address-space template self-check passed: kernel_shared=true user_window_empty=true kernel_probe_typed=true kernel_root_typed=true",
    "User address-space reclaim self-check passed: user_pages=1 page_table_pages=4",
    "Kernel task stack prepared: .*guard_unmapped=true writable_mapped=true kernel_stack_top_typed=true context_stack_top_typed=true",
    "Kernel stack guard diagnostics verified: .*guard_fault_address_typed=true kernel_stack_page_starts_typed=true",
    "User return stack address self-check passed: user_return_stack_address_typed=true user_return_stack_storage_private=true",
    "Page fault report self-check passed: page_fault_report_typed=true fault_address_typed=true instruction_pointer_typed=true error_bits_typed=true",
    "User program spawn errno smoke passed: missing=-2 relative=-22 directory=-21 device=-95 invalid_image=-22 oom=-12",
    "Loading user ELF from filesystem: path=/disk/bin/smoke_demo",
    "User address space prepared: pml4=",
    "ELF header validated: .*entry_point_typed=true",
    "ELF segment mapped: .*perms=R-X .*segment_range_typed=true page_range_typed=true file_backed_range_typed=true",
    "ELF segment mapped: .*perms=R-- .*segment_range_typed=true page_range_typed=true file_backed_range_typed=true",
    "ELF segment mapped: .*perms=RW- .*segment_range_typed=true page_range_typed=true file_backed_range_typed=true",
    "User ELF demo loaded: .*heap_start_typed=true",
    "User stack mapping verified: pages=4 .*guard_unmapped=true page_count_typed=true",
    "Kernel/user mapping permission self-check passed: .*permission_addresses_typed=true permission_page_bounds_typed=true",
    "Syscall user data permission self-check passed: permission_addresses_typed=true permission_page_bounds_typed=true",
    "User program entry vectors staged: argument_count=2 environment_count=1",
    "User task spawned\. task_id=.* address_space=",
    "User task current directory inherited: parent=0 child=.* cwd=/",
    "User program spawned from filesystem: task=.* path=/disk/bin/smoke_demo argc=2",
    "Installed user task kernel stack: task=.* address_space=.* kernel_stack_top_typed=true architecture_stack_installer_typed=true privilege_stack_top_typed=true",
    "User trap frame entry prepared: .*trap_frame_user_addresses_typed=true",
    "User entry arguments prepared: argc=2 .*entry_arguments_typed=true",
    "Multi-user smoke tasks spawned",
    "Concurrent user program spawn smoke passed: tasks=5",
    "Multi-user active set prepared: tasks=5",
    "Preempted user exit continuation smoke passed: first_exit=.* remaining_active=true timer_preemptions=[1-9][0-9]* last_preemption_reason=timer last_resume_path=(lifecycle_entry|timer_entry|timer_resume)",
    "Timer interrupt frame self-check passed: timer_frame_typed=true frame_storage_typed=true instruction_pointer_typed=true stack_pointer_typed=true",
    "User timer interrupt frame observed: .*timer_frame_addresses_typed=true",
    "User timer trap frame saved: .*trap_frame_storage_typed=true trap_frame_user_addresses_typed=true",
    "User task preempted by timer",
    "User task entered from preempted user timer context",
    "User task entered from timer context: .*kernel_stack_top_typed=true architecture_stack_installer_typed=true privilege_stack_top_typed=true",
    "User task resumed from timer context: .*kernel_stack_top_typed=true architecture_stack_installer_typed=true privilege_stack_top_typed=true",
    "User task sleep requested: task=.* wake_tick=",
    "User task blocked for sleep: task=.* wake_tick=",
    "User task sleep woke: task=.* wake_tick=.* current_tick=",
    "fstat -> fd=",
    "getdents64 -> fd=",
    "brk -> task=.* mapped_pages=2 brk_request_typed=true",
    "User heap pages unmapped: .*pages=1",
    "brk -> task=.* mapped_pages=1 brk_request_typed=true",
    "mmap -> task=.* pages=3 .*placement=any .*page_count_typed=true mapping_request_typed=true mapping_length_typed=true mapping_start_typed=true",
    "User anonymous mapping unmapped: .*pages=1 records=2 active_pages=2 page_count_typed=true split_start_typed=true record_start_typed=true",
    "munmap -> task=.* pages=1 unmapped=true active_pages=2 active_records=2 unmap_request_typed=true page_count_typed=true",
    "User anonymous mapping unmapped: .*pages=1 records=1 active_pages=1 page_count_typed=true split_start_typed=true record_start_typed=true",
    "munmap -> task=.* pages=1 unmapped=true active_pages=1 active_records=1 unmap_request_typed=true page_count_typed=true",
    "User anonymous mapping unmapped: .*pages=1 records=0 active_pages=0 page_count_typed=true split_start_typed=true record_start_typed=true",
    "munmap -> task=.* pages=1 unmapped=true active_pages=0 active_records=0 unmap_request_typed=true page_count_typed=true",
    "mmap -> task=.* requested=0x600000008000 start=0x600000008000 length=4096 pages=1 .*flags=0x100022 placement=fixed_noreplace .*active_pages=1 .*mapping_request_typed=true mapping_length_typed=true mapping_start_typed=true",
    "User mapping fixed replacement prepared: start=0x600000008000 pages=1 records=0 active_pages=0",
    "mmap -> task=.* requested=0x600000008000 start=0x600000008000 length=4096 pages=1 .*flags=0x32 placement=fixed_replace .*active_pages=1 .*mapping_request_typed=true mapping_length_typed=true mapping_start_typed=true",
    "munmap -> task=.* start=0x600000008000 length=4096 pages=1 unmapped=true active_pages=0 active_records=0 unmap_request_typed=true page_count_typed=true",
    "mmap -> task=.* length=4096 pages=1 protection=0x1 flags=0x2 placement=any source=file_private active_pages=1 file_private_records=1 .*mapping_request_typed=true mapping_length_typed=true mapping_start_typed=true",
    "mmap file preload -> fd=.* offset=0 start=.* length=4096 bytes=.*",
    "User file_private mapping unmapped: .*pages=1 records=0 active_pages=0 page_count_typed=true split_start_typed=true record_start_typed=true",
    "getppid -> parent=0",
    "user process ids ok",
    "user execve validation ok",
    "user syscall errors ok",
    "chdir -> path=/disk",
    "getcwd -> path=/disk bytes=6",
    "user entry arguments ok",
    "User program spawned from filesystem: task=.* path=/disk/bin/file_demo argc=2",
    "spawn -> child=.* path=/disk/bin/file_demo argc=2 envc=1 stack_pages=4",
    "spawn descriptor inheritance selected -> child=.* inherited=[1-9][0-9]* standard=3 close_on_exec=[0-9]+ process_table=true",
    "user spawn vectors ok",
    "user parent exit child alive ok",
    "user orphaned child vectors ok",
    "Orphaned child reparented: old_parent=[1-9][0-9]* child=.* new_parent=0",
    "Orphaned children reparented: old_parent=[1-9][0-9]* new_parent=0 children=1",
    "User task exited: code=7",
    "User task exited: code=43",
    "User task exit status retained: parent=[1-9][0-9]* child=.* code=7 waitable=true",
    "User task exit status retained: parent=0 child=.* code=43 waitable=true",
    "Child exit record retained: parent=[1-9][0-9]* child=.* code=7 waitable=true",
    "Child exit record retained: parent=0 child=.* code=43 waitable=true",
    "Waitable child exit collected: parent=[1-9][0-9]* child=.* code=7",
    "Waitable child exit retained after resource reclaim: parent=0 child=.* code=43 address_space_owned=false kernel_stack_owned=false lifecycle=zombie",
    "Waitable child exit collected: parent=0 child=.* code=43",
    "Parent-exit child-live smoke passed: parent=[1-9][0-9]* child=.* parent_exit_before_child=true retained_parent=false status=11008 reparented=true new_parent=0",
    "User task waitpid requested: task=.* child=any",
    "User task blocked for waitpid: task=.* child=any",
    "User task waitpid woke: parent=[1-9][0-9]* child=.* status=1792",
    "User task waitpid completed: task=.* child=.* status_stored=true",
    "user waitpid blocking nonzero ok",
    "user sleep ok",
    "user shell ok",
    "user bss ok",
    "user heap ok",
    "user mmap ok",
    "user file mmap ok",
    "user smoke ok",
    "User image replaced by execve: task=.* old_address_space=0x[0-9a-f]+ new_address_space=0x[0-9a-f]+ entry=0x400000000000 stack=0x[0-9a-f]+ heap_start=0x[0-9a-f]+ trap_frame_user_addresses_typed=true",
    "execve image published -> task=.* path=/disk/bin/smoke_demo .*argc=2 old_user_pages=12 old_page_table_pages=10 trap_frame_user_addresses_typed=true heap_start_typed=true",
    "close-on-exec descriptors closed: count=[1-9][0-9]*",
    "execve image published -> task=.* path=/disk/bin/file_demo .*argc=1 old_user_pages=10 old_page_table_pages=7 trap_frame_user_addresses_typed=true heap_start_typed=true",
    "user execve success ok",
    "user waitpid no child ok",
    "APIC EOI diagnostics verified: routing_active=true apic_eoi_count=[1-9][0-9]* legacy_eoi_count=0",
    "Interrupt vector diagnostics verified: spurious_vector=255 spurious_count=0 unexpected_external_count=0",
    "Local APIC timer calibration verified: configured=true armed=true masked=true decremented=true expired=false address=0x[0-9a-f]+ apic_mmio_address_typed=true vector=32 divide=16 start_ticks=[0-9]+ current_ticks=[1-9][0-9]* elapsed_ticks=[1-9][0-9]* initial_count=[1-9][0-9]* current_count=[0-9]+ elapsed_counts=[1-9][0-9]* counts_per_tick=[1-9][0-9]* lvt_timer=0x[0-9a-f]+ divide_config=0x3",
    "IOAPIC timer route masked for Local APIC timer: routing_active=true readback_matches=true masked=true timer_gsi=.* table_index=.* low_register=0x[0-9a-f]+ high_register=0x[0-9a-f]+ low_readback=0x[0-9a-f]+ high_readback=0x[0-9a-f]+",
    "Local APIC timer activated: configured=true running=true masked=false periodic=true address=0x[0-9a-f]+ apic_mmio_address_typed=true vector=32 divide=16 activation_ticks=[1-9][0-9]* current_ticks=[1-9][0-9]* initial_count=[1-9][0-9]* current_count=[0-9]+ calibration_counts_per_tick=[1-9][0-9]* lvt_timer=0x[0-9a-f]+ divide_config=0x3",
    "Local APIC timer tick source verified: configured=true running=true masked=false periodic=true address=0x[0-9a-f]+ apic_mmio_address_typed=true vector=32 divide=16 activation_ticks=[1-9][0-9]* current_ticks=[1-9][0-9]* elapsed_ticks=[1-9][0-9]* initial_count=[1-9][0-9]* current_count=[0-9]+ calibration_counts_per_tick=[1-9][0-9]* lvt_timer=0x[0-9a-f]+ divide_config=0x3",
    "Local APIC timer post-smoke verified: configured=true running=true masked=false periodic=true address=0x[0-9a-f]+ apic_mmio_address_typed=true vector=32 divide=16 activation_ticks=[1-9][0-9]* current_ticks=[1-9][0-9]* elapsed_ticks=[1-9][0-9]* initial_count=[1-9][0-9]* current_count=[0-9]+ calibration_counts_per_tick=[1-9][0-9]* lvt_timer=0x[0-9a-f]+ divide_config=0x3",
    "User return preemption window closed: task=.*",
    "User task exited: code=0",
    "User task exit status retained: parent=0 child=.* code=0 waitable=true",
    "Child exit record retained: parent=0 child=.* code=0 waitable=true",
    "Restored kernel address space after user stop",
    "User address space reclaimed: task=.* user_pages=.* page_table_pages=.*",
    "User kernel stack reclaimed: task=.* writable_pages=4 virtual_pages=5",
    "User task resources reclaimed: task=.* address_space=true kernel_stack=true",
    "Active user lifecycle drained: exits=7",
    "Waitable child exit retained after resource reclaim: parent=0 child=.* code=0 address_space_owned=false kernel_stack_owned=false lifecycle=zombie",
    "Waitable child exit collected: parent=0 child=.* code=0",
    "Selected child wait collection verified: parent=0 child=.* status=0",
    "Wait status verified: parent=0 child=.* code=0 status=0",
    "Wait lifecycle smoke passed: parent=0 retained_children=5 collected_children=5 double_reap_prevented=true",
    "Bootstrap child wait collection verified: parent=0 children=5",
    "published_execve_image_snapshots\s+= 3",
    "unreplaced_user_image_snapshots\s+= 7",
    "Multi-user preemption smoke passed: tasks=5",
    "Initial user shell smoke started: task=.* path=/disk/bin/user_shell",
    "user shell ready",
    "user shell tokenizer ok",
    "^builtins: cd exit help pwd$",
    "user shell help ok",
    "^/disk$",
    "user shell pwd ok",
    "^/$",
    "user shell cd root ok",
    "user shell cd disk ok",
    "user shell exit status ok",
    "user shell launching file_demo",
    "user shell file_demo exit ok",
    "user shell launching relative file_demo",
    "user shell relative file_demo exit ok",
    "user shell empty command",
    "user shell token limit reached",
    "user shell argument buffer full",
    "user shell spawn not found",
    "user shell missing command not found ok",
    "user shell bounded errors ok",
    "User task read requested: task=.* fd=0 bytes=128",
    "User task blocked for read: task=.* fd=0 bytes=128",
    "Initial user shell keyboard stdin wait verified: task=.* blocked=true",
    "Initial user shell keyboard stdin prepared: bytes=5",
    "User task read woke: task=.* fd=0 bytes=128",
    "Initial user shell keyboard stdin wake verified: task=.* bytes=5",
    "User task read completed: task=.* result=5",
    "Initial user shell exit collected: parent=0 child=.* status=0",
    "Kernel console available after initial user shell: command=`"pwd`" output_lines=1",
    "Initial user shell smoke passed: task=.* exit_code=0 stdin=keyboard",
    "Scheduler diagnostics verified",
    "Scheduler lifecycle invariants verified",
    "user_tasks\s+= 10",
    "active_user_tasks\s+= 0",
    "active_user_address_spaces\s+= 0",
    "pending_user_exits\s+= 0",
    "retained_user_exit_statuses\s+= 10",
    "waitable_user_exit_statuses\s+= 0",
    "collected_user_exit_statuses\s+= 10",
    "zombie_user_tasks\s+= 0",
    "reaped_user_tasks\s+= 10",
    "preemption_state\s+= enabled",
    "preemption_enabled\s+= true",
    "user_sleep_blocks\s+= 7",
    "user_sleep_wakes\s+= 7",
    "user_waitpid_blocks\s+= 3",
    "user_waitpid_wakes\s+= 3",
    "user_read_blocks\s+= 1",
    "user_read_wakes\s+= 1",
    "waiting_state_transitions\s+= 11",
    "reclaimed_user_resource_records\s+= 10",
    "reclaimed_user_address_spaces\s+= 10",
    "reclaimed_user_pages\s+= 81",
    "reclaimed_user_page_table_pages\s+= 70",
    "reclaimed_user_kernel_stacks\s+= 10",
    "reclaimed_kernel_stack_writable_pages\s+= 40",
    "reclaimed_kernel_stack_virtual_pages\s+= 50",
    "address_space_reclaim_guard_checks\s+= 10",
    "scheduler_transition_invariant_checks\s+= 1",
    "timer_quantum_ticks\s+= 1",
    "timer_user_entries\s+= [1-9][0-9]*",
    "timer_user_entries_from_preempted_user\s+= [1-9][0-9]*",
    "finished_tasks\s+= 10",
    "Scheduler task snapshots verified",
    "rows\s+= 12",
    "finished_user_tasks\s+= 10",
    "bootstrap_child_user_tasks\s+= 7",
    "user_spawned_child_user_tasks\s+= 3",
    "runtime_trap_frame_record_snapshots\s+= 10",
    "preempted_user_task_snapshots\s+= [1-9][0-9]*",
    "full_timer_trap_frame_snapshots\s+= [1-9][0-9]*",
    "full_restored_trap_frame_snapshots\s+= 10",
    "runtime_trap_frame_restore_snapshots\s+= [1-9][0-9]*",
    "resumed_user_task_snapshots\s+= 10",
    "resume_handoff_snapshots\s+= 10",
    "resume_address_space_root_snapshots\s+= 10",
    "resume_kernel_stack_snapshots\s+= 10",
    "resume_snapshot_addresses_typed\s+= true",
    "resume_snapshot_address_accessors_typed\s+= true",
    "fully_reclaimed_user_tasks\s+= 10",
    "user_image_snapshots\s+= 10",
    "typed_user_vm_address_snapshots\s+= 10",
    "user_vm_snapshot_addresses_typed\s+= true",
    "user_vm_snapshot_address_accessors_typed\s+= true",
    "released_mmap_snapshots\s+= 10",
    "Frame allocator diagnostics snapshot",
    "page_table\s+= [0-9]+",
    "user_stack\s+= 0",
    "user_elf\s+= 0",
    "user_heap\s+= 0",
    "user_mapping\s+= 0",
    "dynamic_kernel_mapping\s+= 0",
    "ahci_dma\s+= [0-9]+",
    "last_preemption_reason=timer",
    "last_resume_path=(lifecycle_entry|timer_entry|timer_resume)",
    "Tasks command smoke passed: command=`"tasks`" output_lines=49",
    "Memory command smoke passed: command=`"memory`" output_lines=3",
    "Syscall trace: record=1 task=.* number=39 result=0x",
    "Syscall trace controls smoke passed: command=`"syscalls trace`" records=1",
    "Console status strip smoke passed",
    "ManaOS Boot Summary",
    "SYSTEM HEALTHY"
)

try {
    while ((Get-Date) -lt $deadline) {
        Start-Sleep -Milliseconds 500
        if ($qemu.HasExited) {
            break
        }
        if (Test-Path $SerialLog) {
            $allFound = $true
            foreach ($pattern in $expectedPatterns) {
                if (-not (Select-String -Path $SerialLog -Pattern $pattern -Quiet)) {
                    $allFound = $false
                    break
                }
            }
            if ($allFound) {
                Write-Host "[storage-smoke] PASS"
                foreach ($pattern in $expectedPatterns) {
                    Select-String -Path $SerialLog -Pattern $pattern | Select-Object -First 1
                }
                exit 0
            }
        }
    }

    Write-Host "[storage-smoke] FAIL"
    if (Test-Path $SerialLog) {
        Get-Content $SerialLog -Tail 80
    }
    exit 1
}
finally {
    if (-not $qemu.HasExited) {
        Stop-Process -Id $qemu.Id -Force
        $qemu.WaitForExit()
    }
}
